### ISSUE TITLE
[Windows] Menu Bar appears during playback while in full-screen

### ISSUE THREAD

**Issue by DaedalusBLN** [RedDuckss/stream-box#4]
![stream-box_menubar-in-fullscreen-bug](https://user-images.githubusercontent.com/35345064/62902633-e0f65800-bd68-11e9-95bc-e5b81192a3f5.png)

Is this intentional?

**Comment by DaedalusBLN** [comment]
Also suggesting feature of highest quality source selection (720p/1080p HD sources preferred) and Real-Debrid support.
Thanks for your efforts, I really like where this is heading. :)

**Comment by RedDuckss** [comment]
This was not intentional. I didn't notice I hadn't un-commented the line that removes the menu 😅 it should only show when running from source, and be hidden when running from a build. This has been fixed in the latest push

**Comment by RedDuckss** [comment]
> Also suggesting feature of highest quality source selection (720p/1080p HD sources preferred)

Stream selection is planned. I opted to not select the highest possible quality as I did not want to make any assumptions about a users preference atm (for example users with slower internet might want lower quality video). So for now, it just uses the first stream it can find

> Real-Debrid support

Don't know what Real-Debrid is, but if you could make a separate issue report for this suggestion I'd be happy to continue discussing it there
