### ISSUE TITLE
Server 

### ISSUE THREAD

**Issue by knkrth** [RedDuckss/stream-box#9]
Hi, How to run this on the server & access via browser?

**Comment by jonbarrow** [comment]
You don’t. This is an Electron app, with many parts of it being written assuming it’s run on a desktop. If you want a browser-based version I suggest joining this Discord server https://discord.gg/tRYAGRc the developer of this site is using parts of my code, so it’s essentially what you’re asking for. It isn’t released yet but it’s getting pretty close

**Comment by knkrth** [comment]
Thanks
